apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string
  labels:
    app: random-string
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-string
  template:
    metadata:
      labels:
        app: random-string
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: random-string
          image: docker.io/aartemdevops10/random-string:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082